on:
  push:
    branches: 'main'
  workflow_dispatch:
  release:
    types: [edited]
  pull_request:
    branches:
      - main
jobs:
  scan-and-archive-build-artifacts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.16.1
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
